import Link from 'next/link';
// import { fetchAllActressesByInitial, fetchActressItems } from '@/lib/dmm-api'; // Old API approach
import actressesData from '@/data/actresses.json';
import { DmmActress } from '@/types/dmm';

// Define the interface for the extended actress object matches the JSON
interface ActressWithVideo extends DmmActress {
  hasVideos?: boolean;
}

export default async function Home() {
  // Use data from local file generated by script
  // The script has already filtered them to valid ones (validActresses)
  const filteredActresses: ActressWithVideo[] = actressesData as ActressWithVideo[];

  return (
    <div className="min-h-screen bg-[#0a0a0b] text-[#ededed]">
      <main className="mx-auto max-w-4xl px-4 py-16">
        <h1 className="mb-12 text-center text-4xl font-bold text-transparent bg-clip-text bg-gradient-to-r from-purple-400 to-pink-600">
          VR Actress Database
        </h1>

        <div className="mb-8">
          <h2 className="mb-6 text-2xl font-bold border-b border-gray-800 pb-2">
            「あ」行の女優一覧 (Top {filteredActresses.length})
          </h2>

          <div className="grid grid-cols-2 gap-4 sm:grid-cols-3 md:grid-cols-4">
            {filteredActresses.map((actress) => (
              <Link
                key={actress.id}
                href={`/actress/${actress.id}`}
                className="group block overflow-hidden rounded-lg bg-gray-900 transition hover:bg-gray-800"
              >
                {/* Image Placeholder or Actual Image if available */}
                <div className="aspect-[3/4] w-full bg-gray-800 relative">
                  {actress.imageURL?.large ? (
                    <img
                      src={actress.imageURL.large}
                      alt={actress.name}
                      className="absolute h-full w-full object-cover transition duration-300 group-hover:scale-105"
                      loading="lazy"
                    />
                  ) : (
                    <div className="flex h-full w-full items-center justify-center text-gray-600">
                      No Image
                    </div>
                  )}
                </div>

                <div className="p-3">
                  <h3 className="truncate font-bold text-sm text-gray-200 group-hover:text-white">
                    {actress.name}
                  </h3>
                  {actress.ruby && (
                    <div className="truncate text-xs text-gray-500">
                      {actress.ruby}
                    </div>
                  )}
                </div>
              </Link>
            ))}
          </div>
        </div>

      </main>
    </div>
  );
}
